name: elite_multiservicios_flutter
description: Frontend del Modulo de Recursos Humanos (RRHH) - Elite Multiservicios

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: '^3.32.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  elite_multiservicios_client:
    path: packages/elite_multiservicios_client
  serverpod_flutter: 3.4.13
  serverpod_auth_idp_flutter: 3.4.13
  google_fonts: ^6.2.1
  crypto: ^3.0.3
  intl: ^0.20.2
  flutter_riverpod: ^3.3.2

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/images/

dependency_overrides:
  flutter_secure_storage: ^10.0.0
